from django.urls import path
from apps.GestionarClinicaVeterinaria.views import (
    HistorialClinicoPorMascotaView,
    ConsultaClinicaListCreateView,
    ConsultaClinicaDetailView,
    TratamientoListCreateView,
    TratamientoDetailView,
    RecetaPorConsultaView,
    RecetaDetailView,
    DetalleRecetaListCreateView,
    DetalleRecetaDetailView,
    VacunaAplicadaListCreateView,
    VacunaAplicadaDetailView,
    ArchivoClinicoListCreateView,
    ArchivoClinicoDetailView,
)

urlpatterns = [
    path(
        "mascotas/<int:id_mascota>/historial/",
        HistorialClinicoPorMascotaView.as_view(),
        name="historial-clinico-por-mascota",
    ),
    path(
        "historiales/<int:id_historial_clinico>/consultas/",
        ConsultaClinicaListCreateView.as_view(),
        name="consulta-clinica-list-create",
    ),
    path(
        "consultas/<int:id_consulta_clinica>/",
        ConsultaClinicaDetailView.as_view(),
        name="consulta-clinica-detail",
    ),
    path(
        "consultas/<int:id_consulta_clinica>/tratamientos/",
        TratamientoListCreateView.as_view(),
        name="tratamiento-list-create",
    ),
    path(
        "tratamientos/<int:id_tratamiento>/",
        TratamientoDetailView.as_view(),
        name="tratamiento-detail",
    ),
    path(
        "consultas/<int:id_consulta_clinica>/receta/",
        RecetaPorConsultaView.as_view(),
        name="receta-por-consulta",
    ),
    path(
        "recetas/<int:id_receta>/",
        RecetaDetailView.as_view(),
        name="receta-detail",
    ),
    path(
        "recetas/<int:id_receta>/detalles/",
        DetalleRecetaListCreateView.as_view(),
        name="detalle-receta-list-create",
    ),
    path(
        "detalles-receta/<int:id_detalle_receta>/",
        DetalleRecetaDetailView.as_view(),
        name="detalle-receta-detail",
    ),
    path(
        "consultas/<int:id_consulta_clinica>/vacunas/",
        VacunaAplicadaListCreateView.as_view(),
        name="vacuna-aplicada-list-create",
    ),
    path(
        "vacunas/<int:id_vacuna_aplicada>/",
        VacunaAplicadaDetailView.as_view(),
        name="vacuna-aplicada-detail",
    ),
    path(
        "consultas/<int:id_consulta_clinica>/archivos/",
        ArchivoClinicoListCreateView.as_view(),
        name="archivo-clinico-list-create",
    ),
    path(
        "archivos/<int:id_archivo_clinico>/",
        ArchivoClinicoDetailView.as_view(),
        name="archivo-clinico-detail",
    ),
]