# Generated by Django 5.2.12 on 2026-04-14 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionClientesyMascotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id_historial_clinico', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('mascota', models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.CASCADE, related_name='historiales_clinicos', to='GestionClientesyMascotas.mascota')),
            ],
            options={
                'verbose_name': 'Historial clínico',
                'verbose_name_plural': 'Historiales clínicos',
                'db_table': 'historial_clinico',
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id_tratamiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('historial_clinico', models.ForeignKey(db_column='id_historial_clinico', on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='GestionClientesyMascotas.historialclinico')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'db_table': 'tratamiento',
            },
        ),
        migrations.CreateModel(
            name='VacunaAplicada',
            fields=[
                ('id_vacuna_aplicada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_vacuna', models.CharField(max_length=100)),
                ('dosis', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_aplicada', models.DateField()),
                ('fecha_proxima', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APLICADA', 'Aplicada'), ('REF', 'Refuerzo')], default='APLICADA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('historial_clinico', models.ForeignKey(db_column='id_historial_clinico', on_delete=django.db.models.deletion.CASCADE, related_name='vacunas_aplicadas', to='GestionClientesyMascotas.historialclinico')),
            ],
            options={
                'verbose_name': 'Vacuna Aplicada',
                'verbose_name_plural': 'Vacunas Aplicadas',
                'db_table': 'vacuna_aplicada',
            },
        ),
    ]
