# Generated by Django 5.2.12 on 2026-06-23 01:10

import apps.GestionClientesyMascotas.models.analisis_imagen_mascota
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionySeguridad', '0025_alter_backupconfig_dias_retención_and_more'),
        ('GestionClientesyMascotas', '0006_adopcion_contacto_ubicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisImagenMascota',
            fields=[
                ('id_analisis_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to=apps.GestionClientesyMascotas.models.analisis_imagen_mascota.analisis_imagen_upload_to)),
                ('calidad_imagen', models.CharField(choices=[('SUFICIENTE', 'Suficiente'), ('INSUFICIENTE', 'Insuficiente'), ('NO_ANALIZABLE', 'No analizable')], default='NO_ANALIZABLE', max_length=20)),
                ('observaciones_visibles', models.JSONField(blank=True, default=list)),
                ('recomendaciones_generales', models.JSONField(blank=True, default=list)),
                ('nivel_atencion', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('URGENTE', 'Urgente'), ('NO_ANALIZABLE', 'No analizable')], default='NO_ANALIZABLE', max_length=20)),
                ('requiere_consulta', models.BooleanField(default=False)),
                ('mensaje_preventivo', models.TextField(blank=True)),
                ('respuesta_ia_raw', models.JSONField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('error_mensaje', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('mascota', models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.CASCADE, related_name='analisis_imagenes', to='GestionClientesyMascotas.mascota')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='analisis_imagenes_mascota', to=settings.AUTH_USER_MODEL)),
                ('veterinaria', models.ForeignKey(db_column='id_veterinaria', on_delete=django.db.models.deletion.PROTECT, related_name='analisis_imagenes_mascota', to='AutenticacionySeguridad.veterinaria')),
            ],
            options={
                'verbose_name': 'Analisis de imagen de mascota',
                'verbose_name_plural': 'Analisis de imagenes de mascotas',
                'db_table': 'analisis_imagen_mascota',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
