# Generated by Django 5.2.12 on 2026-07-06 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionySeguridad', '0025_alter_backupconfig_dias_retención_and_more'),
        ('GestionClientesyMascotas', '0007_analisisimagenmascota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordatorioMascota',
            fields=[
                ('id_recordatorio', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('VACUNA', 'Vacuna'), ('DESPARASITACION', 'Desparasitacion'), ('MEDICAMENTO', 'Medicamento'), ('CONTROL', 'Control'), ('BANIO', 'Banio'), ('PELUQUERIA', 'Peluqueria'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_programada', models.DateField()),
                ('hora_programada', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('notificar', models.BooleanField(default=True)),
                ('dias_anticipacion', models.PositiveIntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('mascota', models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='GestionClientesyMascotas.mascota')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios_mascotas', to=settings.AUTH_USER_MODEL)),
                ('veterinaria', models.ForeignKey(db_column='id_veterinaria', on_delete=django.db.models.deletion.PROTECT, related_name='recordatorios_mascotas', to='AutenticacionySeguridad.veterinaria')),
            ],
            options={
                'verbose_name': 'Recordatorio de Mascota',
                'verbose_name_plural': 'Recordatorios de Mascotas',
                'db_table': 'recordatorio_mascota',
                'indexes': [models.Index(fields=['veterinaria', 'mascota', 'estado', 'fecha_programada'], name='idx_rec_masc_estado')],
            },
        ),
    ]
