# Generated by Django 5.2.12 on 2026-07-06 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionySeguridad', '0025_alter_backupconfig_dias_retención_and_more'),
        ('GestionClientesyMascotas', '0008_recordatoriomascota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEvolucionMascota',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condicion_corporal', models.CharField(choices=[('BAJO', 'Bajo peso'), ('NORMAL', 'Normal'), ('SOBREPESO', 'Sobrepeso'), ('OBESIDAD', 'Obesidad'), ('NO_EVALUADO', 'No evaluado')], default='NO_EVALUADO', max_length=20)),
                ('nota', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('mascota', models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.CASCADE, related_name='registros_evolucion', to='GestionClientesyMascotas.mascota')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='registros_evolucion_mascotas', to=settings.AUTH_USER_MODEL)),
                ('veterinaria', models.ForeignKey(db_column='id_veterinaria', on_delete=django.db.models.deletion.PROTECT, related_name='registros_evolucion_mascotas', to='AutenticacionySeguridad.veterinaria')),
            ],
            options={
                'verbose_name': 'Registro de evolucion de mascota',
                'verbose_name_plural': 'Registros de evolucion de mascotas',
                'db_table': 'registro_evolucion_mascota',
                'ordering': ['-fecha_registro', '-fecha_creacion'],
                'indexes': [models.Index(fields=['mascota', 'fecha_registro'], name='idx_evo_masc_fecha'), models.Index(fields=['veterinaria', 'fecha_registro'], name='idx_evo_vet_fecha')],
            },
        ),
    ]
