# Generated by Django 5.2.12 on 2026-07-06 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionClientesyMascotas', '0009_registroevolucionmascota'),
        ('NotificacionesySeguimiento', '0006_pedido_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordatoriomascota',
            name='fecha_notificacion_enviada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordatoriomascota',
            name='intentos_notificacion',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recordatoriomascota',
            name='notificacion',
            field=models.OneToOneField(blank=True, db_column='id_notificacion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordatorio_mascota', to='NotificacionesySeguimiento.notificacion'),
        ),
        migrations.AddField(
            model_name='recordatoriomascota',
            name='ultimo_error_notificacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recordatoriomascota',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=20),
        ),
    ]
