# Generated by Django 5.2.12 on 2026-07-06 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionySeguridad', '0025_alter_backupconfig_dias_retención_and_more'),
        ('GestionInventarioProveedores', '0012_stock_unique_por_lote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoFavorito',
            fields=[
                ('id_favorito', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='GestionInventarioProveedores.producto')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='productos_favoritos', to=settings.AUTH_USER_MODEL)),
                ('veterinaria', models.ForeignKey(db_column='id_veterinaria', on_delete=django.db.models.deletion.PROTECT, related_name='productos_favoritos', to='AutenticacionySeguridad.veterinaria')),
            ],
            options={
                'verbose_name': 'Producto Favorito',
                'verbose_name_plural': 'Productos Favoritos',
                'db_table': 'producto_favorito',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'producto', 'veterinaria'), name='uq_producto_favorito_usuario_producto_veterinaria')],
            },
        ),
    ]
